import type { OutputFormat, ReportJobRow, ScanReport } from './types.js';

const TOP_MARKDOWN_JOBS = 5;

function formatUsd(value: number): string {
  return `$${value.toFixed(2)}`;
}

function formatPercent(rate: number): string {
  return `${(rate * 100).toFixed(1)}%`;
}

function formatMinutes(value: number): string {
  return value.toFixed(2);
}

function formatDate(iso: string): string {
  return iso.slice(0, 10);
}

function padRight(value: string, width: number): string {
  return value.length >= width ? value : value + ' '.repeat(width - value.length);
}

function padLeft(value: string, width: number): string {
  return value.length >= width ? value : ' '.repeat(width - value.length) + value;
}

const TABLE_HEADERS = ['Job', 'Runs', 'Flaky', 'Rate', 'Wasted min', 'USD'];

function jobToTableRow(job: ReportJobRow): string[] {
  return [
    job.jobName,
    String(job.sampleSize),
    String(job.flakyRuns),
    formatPercent(job.flakinessRate),
    formatMinutes(job.wastedMinutes),
    formatUsd(job.costUsd),
  ];
}

export function renderTable(report: ScanReport): string {
  const rows = report.jobs.map(jobToTableRow);
  const allRows = [TABLE_HEADERS, ...rows];
  const widths = TABLE_HEADERS.map((_, col) => Math.max(...allRows.map((row) => row[col]?.length ?? 0)));

  const formatRow = (row: string[]): string =>
    row.map((cell, col) => (col === 0 ? padRight(cell, widths[col]!) : padLeft(cell, widths[col]!))).join('  ');

  const lines: string[] = [];
  lines.push(`Veedor CI report for ${report.repo}${report.workflow ? ` (workflow: ${report.workflow})` : ''}`);
  lines.push(
    `Runs analyzed: ${report.runsAnalyzed} (${formatDate(report.dateRange.from)} to ${formatDate(
      report.dateRange.to,
    )}, ${report.analyzedDays.toFixed(1)} days)`,
  );
  lines.push('');
  lines.push(formatRow(TABLE_HEADERS));
  lines.push(widths.map((width) => '-'.repeat(width)).join('  '));

  if (rows.length === 0) {
    lines.push('(no flaky jobs detected)');
  } else {
    for (const row of rows) {
      lines.push(formatRow(row));
    }
  }

  lines.push('');
  lines.push(`Total wasted: ${formatMinutes(report.totalWastedMinutes)} min — ${formatUsd(report.totalCostUsd)}`);
  lines.push(`Projected monthly cost: ${formatUsd(report.projectedMonthlyCostUsd)}`);

  return lines.join('\n');
}

export function renderJson(report: ScanReport): string {
  return JSON.stringify(report, null, 2);
}

export function renderMarkdown(report: ScanReport): string {
  const top = report.jobs.slice(0, TOP_MARKDOWN_JOBS);
  const lines: string[] = [];

  lines.push(`## Veedor CI report — ${report.repo}`);
  lines.push('');
  lines.push(
    `**Total wasted spend: ${formatUsd(report.totalCostUsd)}** across ${report.runsAnalyzed} runs analyzed ` +
      `(${formatDate(report.dateRange.from)} to ${formatDate(report.dateRange.to)}, ~${report.analyzedDays.toFixed(
        1,
      )} days) — projected **${formatUsd(report.projectedMonthlyCostUsd)}/month** if this trend holds.`,
  );
  lines.push('');
  if (top.length === 0) {
    lines.push('### Flakiest jobs');
    lines.push('');
    lines.push('No flaky jobs detected in this range.');
  } else {
    lines.push(`### Top ${top.length} flakiest jobs`);
    lines.push('');
    lines.push('| Job | Runs | Flaky | Rate | Wasted min | USD |');
    lines.push('| --- | ---: | ---: | ---: | ---: | ---: |');
    for (const job of top) {
      lines.push(
        `| ${job.jobName} | ${job.sampleSize} | ${job.flakyRuns} | ${formatPercent(job.flakinessRate)} | ${formatMinutes(
          job.wastedMinutes,
        )} | ${formatUsd(job.costUsd)} |`,
      );
    }
  }

  lines.push('');
  lines.push(`<sub>Generated by veedor-ci on ${formatDate(report.generatedAt)}.</sub>`);

  return lines.join('\n');
}

export function renderReport(report: ScanReport, format: OutputFormat): string {
  switch (format) {
    case 'table':
      return renderTable(report);
    case 'json':
      return renderJson(report);
    case 'markdown':
      return renderMarkdown(report);
    default: {
      const exhaustive: never = format;
      throw new Error(`Unsupported format: ${String(exhaustive)}`);
    }
  }
}
